/* wispc codegen — top-level: outputs.c, main.c, override emit, entry.
 *
 * Split from codegen.c. Helpers live in codegen_util.c (eval_*),
 * codegen_sources.c (source drivers + gen_sources/gen_bindings emit),
 * codegen_expr.c (expression lowerer), codegen_items.c (bar items +
 * surface click dispatch + emit_stmt), codegen_surface.c (emit_generated_surface,
 * emit_generated_compound, emit_surfaces). Shared types and prototypes are in
 * codegen_internal.h. */

#include "codegen_internal.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

/* ============================================================ */
/* outputs.c + main.c emit                                       */
/* ============================================================ */

static int emit_outputs(FILE *o, Unit *u, SemaResult *r) {
    fputs("/* Generated by wispc. Do not edit. */\n", o);
    fputs("#include \"wisp.h\"\n\n", o);

    /* Forward decls for surface create_on entry points. */
    for (int i = 0; i < u->n; i++) {
        Decl *d = u->decls[i];
        if (d->kind != D_SURFACE && d->kind != D_COMPOUND) continue;
        if (d->kind == D_SURFACE && surface_prop(d, "spawned_by")) continue;
        fprintf(o, "extern void %.*s_create_on(Output *);\n", (int)d->nlen, d->name);
        fprintf(o, "extern int  %.*s_is_visible(void);\n", (int)d->nlen, d->name);
    }
    if (r->has_wallpaper) fputs("extern void wall_create_on(Output *);\n", o);
    fputs("extern void lock_on_output_added(Output *);\n", o);
    fputs("extern int  lock_active(void);\n", o);
    fputs("extern void gamma_bind_output(Output *);\n", o);

    fputs("\nvoid output_init_widgets(Output *o) {\n", o);
    fputs("    if (!o || o->widgets_created) return;\n", o);
    fputs("    if (!id_compositor || !id_layer_shell) return;\n", o);
    if (r->has_gamma)
        fputs("    if (id_gamma_mgr && !o->gamma_ctrl && !o->gamma_failed) gamma_bind_output(o);\n", o);
    if (r->has_wallpaper)
        fputs("    wall_create_on(o);\n", o);
    /* Each generated surface, in declared order. */
    for (int i = 0; i < u->n; i++) {
        Decl *d = u->decls[i];
        if (d->kind != D_SURFACE && d->kind != D_COMPOUND) continue;
        if (d->kind == D_SURFACE && surface_prop(d, "spawned_by")) continue;
        if (surface_prop(d, "visible"))
            fprintf(o, "    if (%.*s_is_visible()) %.*s_create_on(o);\n",
                    (int)d->nlen, d->name, (int)d->nlen, d->name);
        else
            fprintf(o, "    %.*s_create_on(o);\n", (int)d->nlen, d->name);
    }
    fputs("    o->widgets_created = 1;\n", o);
    /* Lock now lives in the wisp-lock binary; no hook into the daemon's
     * per-output init. See src/lock-features.h. */
    fputs("    if (!focused_output) focused_output = o;\n", o);
    fputs("}\n", o);
    return 0;
}

/* ============================================================ */
/* main.c                                                        */
/* ============================================================ */

static void emit_main(FILE *o, SrcInst *srcs, int nsrc, SemaResult *r) {
    fputs("/* Generated by wispc. Do not edit. Boot + epoll tailored to config. */\n", o);
    fputs("#include \"wisp.h\"\n#include <errno.h>\n#include <signal.h>\n#include <stdio.h>\n"
          "#include <stdlib.h>\n#include <string.h>\n#include <unistd.h>\n#include <sys/epoll.h>\n"
          "#include <sys/timerfd.h>\n\n", o);
    fputs("static int ep_fd = -1;\n", o);

    for (int i = 0; i < nsrc; i++) {
        SrcInst *s = &srcs[i];
        const char *nm = sname(s->decl->name, s->decl->nlen);
        if (s->drv->drv == DRV_CLOCK)
            fprintf(o, "extern int src_%s_fd; void src_%s_init(void); void src_%s_handle(void);\n",
                    nm, nm, nm);
        else if (s->drv->drv == DRV_EXEC)
            fprintf(o, "extern int src_%s_fd; extern int src_%s_pipe; void src_%s_init(void); void src_%s_handle(void); void src_%s_handle_pipe(void);\n",
                    nm, nm, nm, nm, nm);
        else if (s->drv->drv == DRV_DBUS)
            fprintf(o, "void src_%s_init(void);\n", nm);
    }
    if ((has_dbus_src(srcs, nsrc) || r->has_dbus))
        fputs("int dbus_connect(void); void dbus_dispatch(void);\n"
              "extern int dbus_fd; extern int dbus_reconnect_fd;\n"
              "void dbus_reconnect_init(void); void dbus_reconnect_handle(void);\n", o);
    if (has_status_src(srcs, nsrc))
        fputs("extern int wispgen_status_tfd; void wispgen_status_init(void); void wispgen_status_handle(void);\n", o);
    /* lock_helper_fd / lock_on_helper_event live in wisp-lock now. */
    if (r->has_gamma)
        fputs("void gamma_init(void); void gamma_tick(int tick_n);\n", o);

    for (int i = 0; i < r->nsurfaces; i++) {
        const char *sn = r->surface_names[i];
        int is_template = 0;
        for (int j = 0; j < r->nspawned; j++)
            if (strcmp(sn, r->spawned_names[j]) == 0) { is_template = 1; break; }
        fprintf(o, "extern int dirty_%s;\n", sn);
        fprintf(o, "void %s_apply_visibility(void);\n", sn);
        if (!is_template) fprintf(o, "void %s_redraw(void);\n", sn);
    }
    fputc('\n', o);

    fputs("void epoll_add_fd(int fd) {\n"
          "    if (ep_fd < 0 || fd < 0) return;\n"
          "    struct epoll_event ev = { .events = EPOLLIN, .data.fd = fd };\n"
          "    epoll_ctl(ep_fd, EPOLL_CTL_ADD, fd, &ev);\n"
          "}\n"
          "void epoll_del_fd(int fd) {\n"
          "    if (ep_fd < 0 || fd < 0) return;\n"
          "    epoll_ctl(ep_fd, EPOLL_CTL_DEL, fd, NULL);\n"
          "}\n\n", o);

    fputs("static void on_signal(int s) { (void)s; ctl_close(); _exit(0); }\n\n", o);

    fputs("int main(int argc, char **argv) {\n", o);
    fputs("    signal(SIGINT, on_signal); signal(SIGTERM, on_signal); signal(SIGPIPE, SIG_IGN);\n", o);
    /* SIG_IGN auto-reaps children (Linux/POSIX.1): spawn_autolayout et al. fork
     * per tag-switch/focus and want no exit status — else they pile up as
     * zombies until RLIMIT_NPROC kills all spawning. exec_line sources still
     * waitpid() their own pid; ECHILD there just makes them re-kick. */
    fputs("    signal(SIGCHLD, SIG_IGN);\n", o);
    /* --reload-fds wl=N,ctl=M : adopt inherited fds (Step H). */
    fputs("    int reload_wl = -1, reload_ctl = -1;\n", o);
    fputs("    for (int i = 1; i + 1 < argc; i++)\n"
          "        if (!strcmp(argv[i], \"--reload-fds\"))\n"
          "            sscanf(argv[i+1], \"wl=%d,ctl=%d\", &reload_wl, &reload_ctl);\n", o);
    fputs("    if (reload_wl >= 0) wl_adopt(reload_wl); else wl_connect();\n", o);
    fputs("    if (!id_compositor)  die(\"compositor missing\");\n", o);
    fputs("    if (!id_shm)         die(\"wl_shm missing\");\n", o);
    fputs("    if (!id_layer_shell) die(\"layer-shell missing\");\n", o);
    fputs("    for (int i = 0; i < MAX_OUTPUTS; i++)\n"
          "        if (outputs[i].active) output_init_widgets(&outputs[i]);\n", o);
    fputs("    if (reload_ctl >= 0) ctl_adopt(reload_ctl); else ctl_open();\n", o);
    fputs("    key_rep_tfd = timerfd_create(CLOCK_MONOTONIC, TFD_CLOEXEC | TFD_NONBLOCK);\n", o);
    if (has_status_src(srcs, nsrc)) fputs("    wispgen_status_init();\n", o);
    if (r->has_gamma) fputs("    gamma_init();\n", o);
    /* Standalone 1Hz tick for gamma when no status sources are running. */
    if (r->has_gamma && !has_status_src(srcs, nsrc)) {
        fputs("    int wispgen_gamma_tfd = timerfd_create(CLOCK_MONOTONIC, TFD_CLOEXEC | TFD_NONBLOCK);\n", o);
        fputs("    { struct itimerspec ts = { .it_value = {.tv_sec=1}, .it_interval = {.tv_sec=1} };\n"
              "      timerfd_settime(wispgen_gamma_tfd, 0, &ts, NULL); }\n", o);
    }
    for (int i = 0; i < nsrc; i++)
        if (srcs[i].drv->drv == DRV_CLOCK || srcs[i].drv->drv == DRV_EXEC)
            fprintf(o, "    src_%s_init();\n", sname(srcs[i].decl->name, srcs[i].decl->nlen));
    /* DBUS source init must run before dbus_connect() so AddMatch is sent
     * as part of the connect ramp-up. */
    for (int i = 0; i < nsrc; i++)
        if (srcs[i].drv->drv == DRV_DBUS)
            fprintf(o, "    src_%s_init();\n", sname(srcs[i].decl->name, srcs[i].decl->nlen));
    if ((has_dbus_src(srcs, nsrc) || r->has_dbus))
        fputs("    dbus_reconnect_init();\n"
              "    dbus_connect();\n", o);

    fputs("    tags_init();\n", o);
    fputs("    ep_fd = epoll_create1(EPOLL_CLOEXEC);\n", o);
    fputs("    epoll_add_fd(wl_fd);\n", o);
    fputs("    if (tags_fd >= 0) epoll_add_fd(tags_fd);\n", o);
    fputs("    epoll_add_fd(ctl_fd);\n", o);
    fputs("    if (key_rep_tfd >= 0) epoll_add_fd(key_rep_tfd);\n", o);
    if (has_status_src(srcs, nsrc)) fputs("    epoll_add_fd(wispgen_status_tfd);\n", o);
    if ((has_dbus_src(srcs, nsrc) || r->has_dbus))
        fputs("    if (dbus_fd >= 0) epoll_add_fd(dbus_fd);\n"
              "    epoll_add_fd(dbus_reconnect_fd);\n", o);
    if (r->has_gamma && !has_status_src(srcs, nsrc))
        fputs("    epoll_add_fd(wispgen_gamma_tfd);\n", o);
    for (int i = 0; i < nsrc; i++)
        if (srcs[i].drv->drv == DRV_CLOCK || srcs[i].drv->drv == DRV_EXEC)
            fprintf(o, "    epoll_add_fd(src_%s_fd);\n", sname(srcs[i].decl->name, srcs[i].decl->nlen));

    fputs("    msg(\"wisp: running (generated)\");\n", o);
    fputs("    for (;;) {\n", o);
    fputs("        int __timeout = -1;\n", o);
    if (r->has_hud)
        fputs("        { int __t = hud_check_deferred(now_ms()); if (__t >= 0 && (__timeout < 0 || __t < __timeout)) __timeout = __t; }\n", o);
    if (r->has_osd)
        fputs("        { int __t = osd_check_expiry(now_ms()); if (__t >= 0 && (__timeout < 0 || __t < __timeout)) __timeout = __t; }\n", o);
    fputs("        struct epoll_event evs[16];\n", o);
    fputs("        int n = epoll_wait(ep_fd, evs, 16, __timeout);\n", o);
    fputs("        if (n < 0) { if (errno == EINTR) continue; die(\"epoll_wait: %s\", strerror(errno)); }\n", o);
    fputs("        for (int i = 0; i < n; i++) {\n", o);
    fputs("            int fd = evs[i].data.fd;\n", o);
    fputs("            if (fd == wl_fd) {\n"
          "                while (wl_recv(0) == 0 && wl_rlen >= 8) { wl_dispatch(); if (wl_rlen == 0) break; }\n"
          "            } else if (fd == ctl_fd) {\n"
          "                ctl_accept();\n"
          "            } else if (tags_fd >= 0 && fd == tags_fd) {\n"
          "                tags_dispatch();\n", o);
    /* Key-repeat timer: re-deliver the held key to the focused menu/lock
     * surface. Wayland delivers a single key event; clients owe their own
     * repeat, driven off the compositor's repeat_info (see on_keyboard_event). */
    fputs("            } else if (fd == key_rep_tfd) {\n"
          "                uint64_t exp; (void)!read(key_rep_tfd, &exp, sizeof exp);\n"
          "                if (key_rep_key) {\n"
          "                    Widget *w = widget_by_surface(kbd_focus);\n"
          "                    (void)w;\n"
          "#ifdef WISP_HAS_MENU\n"
          "                    if (w && w->kind == W_MENU) { menu_on_key(w, key_rep_key, 1); continue; }\n"
          "#endif\n"
          "#ifdef WISP_HAS_LOCK\n"
          "                    if (w && w->kind == W_LOCK) { lock_on_key(w, key_rep_key, 1, 0); continue; }\n"
          "#endif\n"
          "                    key_rep_cancel();\n"
          "                }\n", o);
    if (has_status_src(srcs, nsrc)) {
        fputs("            } else if (fd == wispgen_status_tfd) {\n"
              "                wispgen_status_handle();\n", o);
        if (r->has_gamma)
            fputs("                gamma_tick(0);\n", o);
    }
    if (r->has_gamma && !has_status_src(srcs, nsrc)) {
        fputs("            } else if (fd == wispgen_gamma_tfd) {\n"
              "                uint64_t _e; (void)!read(wispgen_gamma_tfd, &_e, sizeof _e);\n"
              "                gamma_tick(0);\n", o);
    }
    /* lock helper is polled by the wisp-lock binary's own main loop. */
    if ((has_dbus_src(srcs, nsrc) || r->has_dbus))
        fputs("            } else if (dbus_fd >= 0 && fd == dbus_fd) {\n"
              "                dbus_dispatch();\n"
              "            } else if (fd == dbus_reconnect_fd) {\n"
              "                dbus_reconnect_handle();\n", o);
    if (r->has_anim)
        fputs("            } else if (fd == anim_fd()) {\n"
              "                anim_on_tfd();\n", o);
    for (int i = 0; i < nsrc; i++) {
        if (srcs[i].drv->drv != DRV_CLOCK && srcs[i].drv->drv != DRV_EXEC) continue;
        const char *nm = sname(srcs[i].decl->name, srcs[i].decl->nlen);
        fprintf(o, "            } else if (fd == src_%s_fd) {\n"
                   "                src_%s_handle();\n", nm, nm);
        if (srcs[i].drv->drv == DRV_EXEC)
            fprintf(o, "            } else if (src_%s_pipe >= 0 && fd == src_%s_pipe) {\n"
                       "                src_%s_handle_pipe();\n", nm, nm, nm);
    }
    fputs("            } else {\n"
          "                Client *c = NULL;\n"
          "                for (int j = 0; j < MAX_CLIENTS; j++)\n"
          "                    if (clients[j].fd == fd) { c = &clients[j]; break; }\n"
          "                if (c) ctl_read(c); else epoll_del_fd(fd);\n"
          "            }\n", o);
    fputs("        }\n", o);
    for (int i = 0; i < r->nsurfaces; i++) {
        const char *sn = r->surface_names[i];
        int is_template = 0;
        for (int j = 0; j < r->nspawned; j++)
            if (strcmp(sn, r->spawned_names[j]) == 0) { is_template = 1; break; }
        if (!is_template)
            fprintf(o, "        if (dirty_%s) { dirty_%s = 0; %s_redraw(); }\n", sn, sn, sn);
        fprintf(o, "        %s_apply_visibility();\n", sn);
    }
    /* Idle tail: drop the font mmap pages FreeType faulted while rasterizing
     * any new glyph this iteration (no-op in non-freetype builds). */
    fputs("        font_ft_trim();\n", o);
    fputs("    }\n", o);
    fputs("}\n", o);
}

/* Find the spawned_by template whose surface name matches `name`. NULL if
 * no such template exists in the unit. */
static Decl *find_spawn_template(Unit *u, const char *name) {
    size_t nlen = strlen(name);
    for (int i = 0; i < u->n; i++) {
        Decl *d = u->decls[i];
        if (d->kind != D_SURFACE) continue;
        if (!surface_prop(d, "spawned_by")) continue;
        if ((size_t)d->nlen == nlen && memcmp(d->name, name, nlen) == 0) return d;
    }
    return NULL;
}

/* Emit gen_overrides.h. The runtime modules (osd_rt.c today, lock/gamma/wall
 * later) get their config.h constants redefined from DSL surface props via
 * `-include gen_overrides.h` ahead of every TU. An always-emitted (possibly
 * empty) file keeps the include unconditional. */
static Decl *find_block(Unit *u, DKind k) {
    for (int i = 0; i < u->n; i++) if (u->decls[i]->kind == k) return u->decls[i];
    return NULL;
}
static Expr *block_prop(Decl *d, const char *name) {
    if (!d) return NULL;
    size_t L = strlen(name);
    for (int i = 0; i < d->block.n; i++) {
        Prop *p = d->block.props[i];
        if (p->nlen == L && memcmp(p->name, name, L) == 0) return p->val;
    }
    return NULL;
}
typedef struct { const char *prop; const char *macro; int kind; } OvMap;
static void emit_block_overrides(FILE *o, Decl *d, const char *label,
                                 const OvMap *map, int nmap, CGCtx *ctx) {
    /* kind: 0=int, 1=color, 2=string (quoted), 3=bool (1/0) */
    if (!d) return;
    fprintf(o, "/* === %s block overrides === */\n", label);
    for (int i = 0; i < nmap; i++) {
        Expr *e = block_prop(d, map[i].prop);
        if (!e) continue;
        switch (map[i].kind) {
        case 0:
            if (e->kind != EX_INT) continue;
            fprintf(o, "#undef %s\n#define %s %d\n", map[i].macro, map[i].macro, (int)e->i);
            break;
        case 1:
            /* eval_color_ctx follows const chains; a given-but-unresolvable
             * color is a hard error, never a silent fall-through to the
             * config.h default (that was how `border = BORD;` quietly kept
             * the stock teal). */
            fprintf(o, "#undef %s\n#define %s 0x%08xu\n", map[i].macro, map[i].macro,
                    (unsigned)eval_color_ctx(ctx, e, 0));
            break;
        case 2:
            if (e->kind != EX_STRING) continue;
            fprintf(o, "#undef %s\n#define %s \"%.*s\"\n",
                    map[i].macro, map[i].macro, (int)e->str.n, e->str.s);
            break;
        case 3: {
            int v = -1;
            if (e->kind == EX_BOOL) v = e->b ? 1 : 0;
            else if (e->kind == EX_INT) v = e->i ? 1 : 0;
            if (v < 0) continue;
            fprintf(o, "#undef %s\n#define %s %d\n", map[i].macro, map[i].macro, v);
            break;
        }
        }
    }
    fputc('\n', o);
}

/* Does an anchor-style expr (`bottom | right`) mention the given ident? */
static bool expr_has_ident(const Expr *e, const char *name) {
    if (!e) return false;
    switch (e->kind) {
    case EX_IDENT:
        return e->ident.n == strlen(name) && memcmp(e->ident.s, name, e->ident.n) == 0;
    case EX_BIN:
        return expr_has_ident(e->bin.l, name) || expr_has_ident(e->bin.r, name);
    case EX_UN:
        return expr_has_ident(e->un.e, name);
    default:
        return false;
    }
}

static void emit_overrides(FILE *o, Unit *u, CGCtx *ctx) {
    fputs("/* Generated by wispc. Do not edit. */\n", o);
    fputs("#ifndef WISP_GEN_OVERRIDES_H\n#define WISP_GEN_OVERRIDES_H\n\n", o);

    /* lock block */
    static const OvMap lockmap[] = {
        {"pam",        "LOCK_PAM_SERVICE", 2},
        {"prompt",     "LOCK_PROMPT",      2},
        {"bg",         "LOCK_BG",          1},
        {"ring",       "LOCK_RING",        1},
        {"ring_bad",   "LOCK_RING_WRONG",  1},
        {"fg",         "LOCK_FG",          1},
        {"dim",        "LOCK_DIM",         1},
        {"caps",       "LOCK_CAPS",        1},
        {"clock_size", "LOCK_CLOCK_SIZE",  0},
        {"font_size",  "LOCK_FONT_SIZE",   0},
        {"wrong_ms",   "LOCK_WRONG_MS",    0},
    };
    emit_block_overrides(o, find_block(u, D_LOCK), "lock", lockmap,
                         (int)(sizeof lockmap / sizeof lockmap[0]), ctx);

    /* gamma block */
    static const OvMap gammamap[] = {
        {"day_k",      "GAMMA_DAY_K",      0},
        {"night_k",    "GAMMA_NIGHT_K",    0},
        {"flat_k",     "GAMMA_FLAT_K",     0},
        {"day_hour",   "GAMMA_DAY_HOUR",   0},
        {"night_hour", "GAMMA_NIGHT_HOUR", 0},
    };
    emit_block_overrides(o, find_block(u, D_GAMMA), "gamma", gammamap,
                         (int)(sizeof gammamap / sizeof gammamap[0]), ctx);

    /* wallpaper block */
    static const OvMap wallmap[] = {
        {"path",       "WALL_PATH",        2},
        {"bg",         "WALL_BG",          1},
    };
    emit_block_overrides(o, find_block(u, D_WALLPAPER), "wallpaper", wallmap,
                         (int)(sizeof wallmap / sizeof wallmap[0]), ctx);

    Decl *osd = find_spawn_template(u, "osd");
    if (osd) {
        fputs("/* === osd surface overrides === */\n", o);
        /* Boolean toggles → 1/0 #defines. true/false are EX_IDENT in the
         * DSL today (no dedicated EX_BOOL). */
        struct { const char *prop; const char *macro; } bools[] = {
            {"focus_follow",     "OSD_FOCUS_FOLLOW"},
            {"dbus_close",       "OSD_DBUS_CLOSE"},
            {"dismiss_on_click", "OSD_DISMISS_ON_CLICK"},
        };
        for (size_t i = 0; i < sizeof(bools)/sizeof(bools[0]); i++) {
            Expr *e = surface_prop(osd, bools[i].prop);
            if (!e) continue;
            int v = -1;
            if (e->kind == EX_BOOL) v = e->b ? 1 : 0;
            else if (e->kind == EX_IDENT) {
                if (e->ident.n == 4 && memcmp(e->ident.s, "true",  4) == 0) v = 1;
                else if (e->ident.n == 5 && memcmp(e->ident.s, "false", 5) == 0) v = 0;
            } else if (e->kind == EX_INT) v = e->i ? 1 : 0;
            if (v < 0) continue;
            fprintf(o, "#undef %s\n#define %s %d\n",
                    bools[i].macro, bools[i].macro, v);
        }
        struct { const char *prop; const char *macro; int is_color; } map[] = {
            {"max",            "MAX_OSDS",            0},
            {"width",          "OSD_W",               0},
            {"height",         "OSD_SLAB_H",          0},
            {"margin",         "OSD_TOP_MARGIN",      0},
            {"gap",            "OSD_GAP",             0},
            {"pad_x",          "OSD_PAD_X",           0},
            {"icon_gap",       "OSD_ICON_GAP",        0},
            {"prog_h",         "OSD_PROG_H",          0},
            {"body_lines",     "OSD_MAX_BODY_LINES",  0},
            {"body_max",       "OSD_BODY_MAX",        0},
            {"timeout_low",    "OSD_TIMEOUT_LOW",     0},
            {"timeout_normal", "OSD_TIMEOUT_NORMAL",  0},
            {"timeout",        "OSD_TIMEOUT_OSD",     0},
            {"slide_ms",       "OSD_SLIDE_MS",        0},
            {"radius",         "OSD_RADIUS",          0},
            {"fillet_r",       "OSD_FILLET_R",        0},
            {"border_width",   "OSD_BORDER_W",        0},
            {"pill_w",         "OSD_PILL_W",          0},
            {"pill_h",         "OSD_PILL_H",          0},
            {"pill_margin",    "OSD_PILL_MARGIN",     0},
            {"pill_radius",    "OSD_PILL_RADIUS",     0},
            {"bg",             "OSD_BG",              1},
            {"fg",             "OSD_FG",              1},
            {"border",         "OSD_BORDER",          1},
            {"prog_fg",        "OSD_PROG_FG",         1},
            {"prog_track",     "OSD_PROG_TRACK_BG",   1},
        };
        for (size_t i = 0; i < sizeof(map)/sizeof(map[0]); i++) {
            Expr *e = surface_prop(osd, map[i].prop);
            if (!e) continue;
            if (map[i].is_color) {
                fprintf(o, "#undef %s\n#define %s 0x%08xu\n",
                        map[i].macro, map[i].macro,
                        (unsigned)eval_color_ctx(ctx, e, 0));
            } else {
                if (e->kind != EX_INT) continue;
                fprintf(o, "#undef %s\n#define %s %d\n",
                        map[i].macro, map[i].macro, (int)e->i);
            }
        }
        /* anchor: only top-center (default) and bottom|right are wired in
         * osd.c; `bottom` anywhere in the anchor expr selects the latter. */
        Expr *a = surface_prop(osd, "anchor");
        if (a && expr_has_ident(a, "bottom"))
            fputs("#undef OSD_ANCHOR_BR\n#define OSD_ANCHOR_BR 1\n", o);
        fputs("\n", o);
    }

    /* menu template → MENU_* overrides consumed by menu.c/apps.c (same
     * osd-style prop→macro flow; menu.c owns the render loop). */
    Decl *menu = find_spawn_template(u, "menu");
    if (menu) {
        fputs("/* === menu surface overrides === */\n", o);
        struct { const char *prop; const char *macro; int is_color; } map[] = {
            {"height",       "MENU_HEIGHT",     0},
            {"pad_x",        "MENU_PAD_X",      0},
            {"item_pad_x",   "MENU_ITEM_PAD_X", 0},
            {"gap",          "MENU_GAP",        0},
            {"width",        "MENU_W",          0},
            {"margin",       "MENU_MARGIN",     0},
            {"max_visible",  "MENU_MAX_VIS",    0},
            {"row_h",        "MENU_ROW_H",      0},
            {"radius",       "MENU_RADIUS",     0},
            {"border_width", "MENU_BORDER_W",   0},
            {"bg",           "MENU_BG",         1},
            {"fg",           "MENU_FG",         1},
            {"sel_bg",       "MENU_SEL_BG",     1},
            {"sel_fg",       "MENU_SEL_FG",     1},
            {"dim",          "MENU_DIM",        1},
            {"border",       "MENU_BORDER",     1},
        };
        for (size_t i = 0; i < sizeof(map)/sizeof(map[0]); i++) {
            Expr *e = surface_prop(menu, map[i].prop);
            if (!e) continue;
            if (map[i].is_color)
                fprintf(o, "#undef %s\n#define %s 0x%08xu\n",
                        map[i].macro, map[i].macro,
                        (unsigned)eval_color_ctx(ctx, e, 0));
            else if (e->kind == EX_INT)
                fprintf(o, "#undef %s\n#define %s %d\n",
                        map[i].macro, map[i].macro, (int)e->i);
        }
        Expr *e = surface_prop(menu, "prompt");
        if (e && e->kind == EX_STRING)
            fprintf(o, "#undef MENU_PROMPT\n#define MENU_PROMPT \"%.*s\"\n",
                    (int)e->str.n, e->str.s);
        e = surface_prop(menu, "axis");
        if (e && expr_has_ident(e, "vertical"))
            fputs("#undef MENU_VERTICAL\n#define MENU_VERTICAL 1\n", o);
        e = surface_prop(menu, "sort");
        if (e && e->kind == EX_STRING) {
            int freq = !(e->str.n == 12 && memcmp(e->str.s, "alphabetical", 12) == 0);
            fprintf(o, "#undef MENU_SORT_FREQ\n#define MENU_SORT_FREQ %d\n", freq);
        }
        fputs("\n", o);
    }

    fputs("#endif\n", o);
}

/* ============================================================ */
/* Entry point                                                   */
/* ============================================================ */

int codegen_emit(const char *dir, Unit *u, SemaResult *r) {
    SrcInst srcs[32];
    int nsrc = collect_srcs(u, srcs, 32);
    if (nsrc < 0) return 1;

    /* Collect const/mut. */
    Decl *konst[64]; int nkonst = 0;
    for (int i = 0; i < u->n; i++)
        if (u->decls[i]->kind == D_CONST || u->decls[i]->kind == D_MUT)
            if (nkonst < 64) konst[nkonst++] = u->decls[i];

    CGCtx ctx = { .srcs = srcs, .nsrc = nsrc, .konst = konst, .nkonst = nkonst, .r = r };

    char path[1024]; FILE *f;
    snprintf(path, sizeof path, "%s/gen_overrides.h", dir);
    f = fopen(path, "w"); if (!f) { perror(path); return 1; }
    emit_overrides(f, u, &ctx); fclose(f);

    snprintf(path, sizeof path, "%s/gen_sources.c", dir);
    f = fopen(path, "w"); if (!f) { perror(path); return 1; }
    emit_sources(f, srcs, nsrc); fclose(f);

    snprintf(path, sizeof path, "%s/gen_bindings.c", dir);
    f = fopen(path, "w"); if (!f) { perror(path); return 1; }
    emit_bindings(f, srcs, nsrc, r, &ctx); fclose(f);

    snprintf(path, sizeof path, "%s/gen_surfaces.c", dir);
    f = fopen(path, "w"); if (!f) { perror(path); return 1; }
    int rc = emit_surfaces(f, u, &ctx); fclose(f);
    if (rc) return rc;

    /* Emit spawn_<name>() shims for every spawned_by template. The args are
     * the $-names sema collected (first-seen order). For "osd" specifically
     * we route through the existing osd_post() runtime; for any other name
     * we emit a no-op stub so emit() callsites link cleanly. Real DSL-driven
     * slot allocator + render is deferred to Session 5b. */
    snprintf(path, sizeof path, "%s/gen_spawn.c", dir);
    f = fopen(path, "w"); if (!f) { perror(path); return 1; }
    fputs("/* Generated by wispc. Do not edit. */\n", f);
    fputs("#include \"wisp.h\"\n#include <string.h>\n\n", f);

    int osd_in_spawn = 0;
    for (int i = 0; i < r->nspawned; i++)
        if (r->spawned_names[i] && strcmp(r->spawned_names[i], "osd") == 0) { osd_in_spawn = 1; break; }

    /* Session 5c: pull the OSD engine into this TU so the DSL drives whether
     * (and with which behavior flags from gen_overrides.h) the engine compiles
     * at all. src/osd.c is no longer linked directly when DSL-spawned. */
    if (osd_in_spawn) {
        fputs("/* === osd engine, instantiated via DSL spawned_by template === */\n", f);
        fputs("#ifdef WISP_HAS_OSD\n", f);
        fputs("#include \"osd.c\"\n", f);
        fputs("#endif\n\n", f);
    }

    for (int i = 0; i < r->nspawned; i++) {
        const char *snm = r->spawned_names[i];
        const char **args = r->spawned_args[i];
        (void)args;
        if (strcmp(snm, "osd") == 0) {
            fputs("#ifdef WISP_HAS_OSD\n", f);
            fputs("void spawn_osd(const char *summary, uint32_t icon, int pct, int muted) {\n"
                  "    osd_post(0, summary ? summary : \"\", \"\", icon, pct, 0, muted, OSD_TIMEOUT_OSD);\n"
                  "}\n", f);
            fputs("#else\n", f);
            fputs("void spawn_osd(const char *s, uint32_t i, int p, int m) { (void)s;(void)i;(void)p;(void)m; }\n", f);
            fputs("#endif\n\n", f);
        } else {
            fprintf(f, "/* spawn_%s: no-op stub; non-osd templates need a generic slot allocator */\n", snm);
            fprintf(f, "void spawn_%s() { }\n\n", snm);
        }
    }
    fclose(f);

    snprintf(path, sizeof path, "%s/gen_outputs.c", dir);
    f = fopen(path, "w"); if (!f) { perror(path); return 1; }
    rc = emit_outputs(f, u, r); fclose(f);
    if (rc) return rc;

    snprintf(path, sizeof path, "%s/main.c", dir);
    f = fopen(path, "w"); if (!f) { perror(path); return 1; }
    emit_main(f, srcs, nsrc, r); fclose(f);

    return 0;
}
