#include "wispc.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/inotify.h>
#include <sys/wait.h>
#include <errno.h>
#include <time.h>

static char *slurp(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc((size_t)n + 1);
    if (fread(buf, 1, (size_t)n, f) != (size_t)n) { free(buf); fclose(f); return NULL; }
    buf[n] = 0; fclose(f);
    return buf;
}

static void emit_features(FILE *o, SemaResult *r) {
    fputs("/* Generated by wispc --emit. Do not edit. */\n", o);
    fputs("#ifndef WISP_GEN_FEATURES_H\n#define WISP_GEN_FEATURES_H\n\n", o);
    #define P(flag, name) do { if (r->flag) fprintf(o, "#define WISP_HAS_%s 1\n", name); } while (0)
    P(has_dbus, "DBUS"); P(has_mpris, "MPRIS"); P(has_tray, "TRAY"); P(has_osd, "OSD"); P(has_menu, "MENU");
    P(has_hud, "HUD");
    /* Overrides the default in wisp.h; force-included, so tray.c's icon buffer
     * and the codegen'd pixmap size agree. */
    if (r->has_tray && r->tray_icon_px)
        fprintf(o, "#define TRAY_ICON_PX %d\n", r->tray_icon_px);
    /* NOTE: has_lock intentionally NOT lowered to WISP_HAS_LOCK in the daemon
     * features.h. The lock state machine lives in a separate binary
     * (wisp-lock); see src/lock-features.h. The DSL `lock {}` block still
     * flows into gen_overrides.h for styling, which wisp-lock consumes. */
    /* WISP_HAS_BAR is implied by any non-special surface (every generated
     * surface uses W_BAR kind, so the wisp.c W_BAR input/render dispatch must
     * be enabled). */
    if (r->has_bar || r->nsurfaces > 0) fputs("#define WISP_HAS_BAR 1\n", o);
    /* Always: gen_outputs.c provides output_init_widgets; wl.c gates its
     * fallback on this. */
    fputs("#define WISP_GENERATED_OUTPUT_INIT 1\n", o);
    P(has_gamma, "GAMMA"); P(has_wallpaper, "WALL"); P(has_media, "MEDIA");
    P(has_anim, "ANIM");
    /* status.c is included whenever any surface might render status text or
     * any sampler is active. bar.c references the global `status` struct
     * unconditionally, so HAS_BAR implies HAS_STATUS. */
    int any_src = r->has_src_cpu || r->has_src_mem || r->has_src_temp ||
                  r->has_src_bat || r->has_src_wifi || r->has_src_disk ||
                  r->has_src_vpn;
    if (r->has_bar || any_src) fputs("#define WISP_HAS_STATUS 1\n", o);
    P(has_src_cpu, "SRC_CPU");   P(has_src_mem, "SRC_MEM");   P(has_src_temp, "SRC_TEMP");
    P(has_src_bat, "SRC_BAT");   P(has_src_wifi, "SRC_WIFI"); P(has_src_disk, "SRC_DISK");
    P(has_src_vpn, "SRC_VPN");   P(has_src_tags, "SRC_TAGS");
    P(has_src_exec, "SRC_EXEC");
    #undef P
    fputs("\n#endif\n", o);
}

static void emit_objects_mk(FILE *o, SemaResult *r) {
    fputs("# Generated by wispc --emit. Do not edit.\n", o);
    fputs("GEN_OBJS := \\\n", o);
    /* always-linked core */
    fputs("    $(BUILD)/wisp.o \\\n", o);
    fputs("    $(BUILD)/wl.o \\\n", o);
    fputs("    $(BUILD)/widget.o \\\n", o);
    fputs("    $(BUILD)/render.o \\\n", o);
    fputs("    $(BUILD)/ctl.o \\\n", o);
    fputs("    $(BUILD)/xkb.o \\\n", o);
    fputs("    $(BUILD)/mango.o \\\n", o);
    fputs("    $(BUILD)/workspace.o \\\n", o);
    int any_src = r->has_src_cpu || r->has_src_mem || r->has_src_temp ||
                  r->has_src_bat || r->has_src_wifi || r->has_src_disk ||
                  r->has_src_vpn;
    if (r->has_bar || any_src)   fputs("    $(BUILD)/status.o \\\n", o);
    /* bar.c is replaced by gen_surfaces.c (which provides bar_render/
     * bar_create_on/bar_redraw_all/bar_set_*). */
    if (r->has_hud)              fputs("    $(BUILD)/hud.o \\\n", o);
    if (r->has_menu)             fputs("    $(BUILD)/menu.o \\\n    $(BUILD)/apps.o \\\n", o);
    /* When an "osd" spawned_by template exists in the unit, gen_spawn.c
     * pulls in the engine via #include "osd.c" (Session 5c). Skip the
     * direct osd.o link to avoid duplicate-definition errors. */
    int osd_via_spawn = 0;
    for (int i = 0; i < r->nspawned; i++)
        if (r->spawned_names[i] && strcmp(r->spawned_names[i], "osd") == 0) { osd_via_spawn = 1; break; }
    if (r->has_osd && !osd_via_spawn) fputs("    $(BUILD)/osd.o \\\n", o);
    if (r->has_wallpaper)        fputs("    $(BUILD)/wall.o \\\n", o);
    /* image.o: PNG decode for the wallpaper, launcher icons (apps.c) and
     * themed tray icons (tray.c). */
    if (r->has_wallpaper || r->has_menu || r->has_tray)
        fputs("    $(BUILD)/image.o \\\n", o);
    /* lock.o lives in wisp-lock, not the daemon — see lock-features.h. */
    if (r->has_gamma)            fputs("    $(BUILD)/gamma.o \\\n", o);
    if (r->has_media)            fputs("    $(BUILD)/media.o \\\n", o);
    if (r->has_dbus)             fputs("    $(BUILD)/dbus.o \\\n    $(BUILD)/notify.o \\\n", o);
    if (r->has_mpris)            fputs("    $(BUILD)/mpris.o \\\n", o);
    if (r->has_tray)             fputs("    $(BUILD)/tray.o \\\n", o);
    if (r->has_anim)             fputs("    $(BUILD)/anim.o \\\n", o);
    fputs("    $(BUILD)/gen_main.o \\\n", o);
    fputs("    $(BUILD)/gen_sources.o \\\n", o);
    fputs("    $(BUILD)/gen_surfaces.o \\\n", o);
    fputs("    $(BUILD)/gen_outputs.o \\\n", o);
    fputs("    $(BUILD)/gen_spawn.o \\\n", o);
    fputs("    $(BUILD)/gen_bindings.o\n", o);
}

static int emit_dir(Unit *u, SemaResult *r, const char *dir) {
    char path[1024];
    snprintf(path, sizeof path, "%s/features.h", dir);
    FILE *f = fopen(path, "w");
    if (!f) { perror(path); return 1; }
    emit_features(f, r); fclose(f);
    snprintf(path, sizeof path, "%s/objects.mk", dir);
    f = fopen(path, "w");
    if (!f) { perror(path); return 1; }
    emit_objects_mk(f, r); fclose(f);
    return codegen_emit(dir, u, r);
}

static void print_features(SemaResult *r) { emit_features(stdout, r); }

static void print_deps(SemaResult *r) {
    for (int i = 0; i < r->nsurfaces; i++) {
        printf("surface %s:", r->surface_names[i]);
        for (int j = 0; r->surface_deps[i][j]; j++)
            printf(" %s", r->surface_deps[i][j]);
        putchar('\n');
    }
}

/* Print one unique font_size per line, ascending. The Makefile pipes the
 * output to `bake` so every size referenced by the unit gets a baked font. */
/* Codepoints the config needs baked: `icon = 0x...` literals and any non-ASCII
 * character in the source. Lexical on purpose — icons hide inside nested
 * ternaries and string interpolations that an AST walk would have to chase. */
static void print_font_glyphs(const char *src) {
    for (const unsigned char *p = (const unsigned char *)src; *p; p++) {
        if (p[0] == '0' && (p[1] == 'x' || p[1] == 'X')) {
            char *end; unsigned long v = strtoul((const char *)p + 2, &end, 16);
            if (end > (char *)p + 2 && v > 0xff && v <= 0x10ffff) printf("+0x%lx\n", v);
            p = (const unsigned char *)end - 1;
        } else if (*p >= 0x80) {
            unsigned n = (*p & 0xe0) == 0xc0 ? 2 : (*p & 0xf0) == 0xe0 ? 3 : (*p & 0xf8) == 0xf0 ? 4 : 1;
            unsigned long cp = n == 1 ? 0 : *p & (0xffu >> (n + 1));
            for (unsigned k = 1; k < n && p[k]; k++) cp = (cp << 6) | (p[k] & 0x3f);
            if (cp > 0x7f) printf("+0x%lx\n", cp);
            p += n - 1;
        }
    }
}

static void print_font_sizes(Unit *u) {
    int sizes[64]; int n = 0;
    for (int i = 0; i < u->n; i++) {
        Decl *d = u->decls[i];
        if (d->kind == D_LOCK) {
            /* lock { clock_size / font_size } sizes must be baked too. */
            for (int j = 0; j < d->block.n; j++) {
                Prop *p = d->block.props[j];
                if ((p->nlen != 10 || memcmp(p->name, "clock_size", 10) != 0) &&
                    (p->nlen != 9  || memcmp(p->name, "font_size",  9) != 0))
                    continue;
                if (!p->val || p->val->kind != EX_INT) continue;
                int v = (int)p->val->i;
                if (v < 4 || v > 256) continue;
                if (n < (int)(sizeof sizes / sizeof *sizes)) sizes[n++] = v;
            }
            continue;
        }
        if (d->kind != D_SURFACE && d->kind != D_COMPOUND) continue;
        for (int j = 0; j < d->surface.n; j++) {
            SBody *b = &d->surface.items[j];
            if (b->kind != SB_PROP) continue;
            Prop *p = b->prop;
            if (p->nlen != 9 || memcmp(p->name, "font_size", 9) != 0) continue;
            if (!p->val || p->val->kind != EX_INT) continue;
            int v = (int)p->val->i;
            if (v < 4 || v > 256) continue;
            if (n < (int)(sizeof sizes / sizeof *sizes)) sizes[n++] = v;
        }
    }
    /* Sort + dedup. */
    for (int i = 1; i < n; i++) {
        int v = sizes[i], k = i;
        while (k > 0 && sizes[k-1] > v) { sizes[k] = sizes[k-1]; k--; }
        sizes[k] = v;
    }
    int last = -1;
    for (int i = 0; i < n; i++) {
        if (sizes[i] == last) continue;
        printf("%d\n", sizes[i]);
        last = sizes[i];
    }
}

static int usage(void) {
    fputs("usage: wispc [--dump-ast | --check | --features | --deps | --font-sizes | --emit DIR | --watch [--reload]] FILE\n", stderr);
    return 2;
}

/* --watch: inotify on FILE; on change, exec `make WISP=FILE`. With --reload,
 * also send `wispctl reload` after a successful build.  Loops until SIGINT. */
static int watch_loop(const char *path, int do_reload) {
    int ifd = inotify_init1(IN_CLOEXEC | IN_NONBLOCK);
    if (ifd < 0) { perror("inotify_init1"); return 1; }
    /* Watch the parent dir + filename to survive editors that replace via rename. */
    char dir[1024]; snprintf(dir, sizeof dir, "%s", path);
    char *slash = strrchr(dir, '/'); const char *base;
    if (slash) { *slash = 0; base = slash + 1; } else { strcpy(dir, "."); base = path; }
    int wd = inotify_add_watch(ifd, dir, IN_CLOSE_WRITE | IN_MOVED_TO | IN_CREATE);
    if (wd < 0) { perror("inotify_add_watch"); return 1; }
    fprintf(stderr, "wispc: watching %s/%s (Ctrl-C to stop)\n", dir, base);

    /* Initial build. */
    char cmd[2048];
    snprintf(cmd, sizeof cmd, "make WISP=%s && %s", path,
             do_reload ? "wispctl reload 2>/dev/null || true" : "true");
    (void)!system(cmd);

    char buf[4096];
    for (;;) {
        ssize_t n = read(ifd, buf, sizeof buf);
        if (n < 0) {
            if (errno == EAGAIN) { struct timespec ts={0,100000000}; nanosleep(&ts,NULL); continue; }
            if (errno == EINTR) continue;
            perror("read"); return 1;
        }
        int hit = 0;
        for (ssize_t off = 0; off + (ssize_t)sizeof(struct inotify_event) <= n; ) {
            struct inotify_event *e = (void*)(buf + off);
            if (e->len && !strcmp(e->name, base)) hit = 1;
            off += sizeof(struct inotify_event) + e->len;
        }
        if (hit) {
            fprintf(stderr, "wispc: change detected, rebuilding...\n");
            (void)!system(cmd);
        }
    }
}

int main(int argc, char **argv) {
    enum { MODE_CHECK, MODE_AST, MODE_FEATURES, MODE_DEPS, MODE_FONTS, MODE_EMIT, MODE_WATCH } mode = MODE_CHECK;
    const char *path = NULL;
    const char *emit_path = NULL;
    int watch_reload = 0;
    for (int i = 1; i < argc; i++) {
        if      (!strcmp(argv[i], "--dump-ast"))   mode = MODE_AST;
        else if (!strcmp(argv[i], "--check"))      mode = MODE_CHECK;
        else if (!strcmp(argv[i], "--features"))   mode = MODE_FEATURES;
        else if (!strcmp(argv[i], "--deps"))       mode = MODE_DEPS;
        else if (!strcmp(argv[i], "--font-sizes")) mode = MODE_FONTS;
        else if (!strcmp(argv[i], "--emit"))       { mode = MODE_EMIT; if (++i >= argc) return usage(); emit_path = argv[i]; }
        else if (!strcmp(argv[i], "--watch"))      mode = MODE_WATCH;
        else if (!strcmp(argv[i], "--reload"))     watch_reload = 1;
        else if (argv[i][0] == '-') return usage();
        else path = argv[i];
    }
    if (!path) return usage();
    if (mode == MODE_WATCH) return watch_loop(path, watch_reload);
    char *src = slurp(path);
    if (!src) return 1;

    Arena *a = arena_new();
    Unit *u = parse_file(a, path, src);
    if (diag_count() > 0) { arena_free(a); free(src); return 1; }
    style_apply(a, u);
    if (diag_count() > 0) { arena_free(a); free(src); return 1; }

    if (mode == MODE_AST)   { dump_unit(stdout, u);   arena_free(a); free(src); return 0; }
    if (mode == MODE_FONTS) { print_font_sizes(u); print_font_glyphs(src); arena_free(a); free(src); return 0; }

    SemaResult *r = sema_check(a, u);
    if (diag_count() > 0) { arena_free(a); free(src); return 1; }

    switch (mode) {
    case MODE_CHECK:    puts("ok"); break;
    case MODE_FEATURES: print_features(r); break;
    case MODE_DEPS:     print_deps(r); break;
    case MODE_EMIT:     if (emit_dir(u, r, emit_path)) { arena_free(a); free(src); return 1; } break;
    default: break;
    }

    arena_free(a); free(src);
    /* Codegen raises diagnostics too (e.g. a compile-time color that does not
     * fold); parse/sema have their own gates, this one catches that last stage
     * so an emitted-but-wrong build cannot exit 0. */
    return diag_count() > 0;
}
