/* Auto-generated by tools/bake.c. Do not edit. */
#ifndef WISP_BAKE_H
#define WISP_BAKE_H
#include <stdint.h>
#include "font.h"

#define WISP_FONT_DEFAULT_PATH "/home/hoks/.local/share/fonts/MapleMono-NF-Bold.ttf"
#define WISP_FONT_FALLBACK_PATH "/usr/share/fonts/noto-emoji/NotoColorEmoji.ttf"

#ifdef WISP_FONT_DEFINE
Font font_14 = { .px_size = 14 };
Font font_20 = { .px_size = 20 };
Font font_22 = { .px_size = 22 };
Font *const wisp_fonts[] = { &font_14, &font_20, &font_22, };
const int wisp_n_fonts = 3;
#else
extern Font font_14;
extern Font font_20;
extern Font font_22;
extern Font *const wisp_fonts[];
extern const int wisp_n_fonts;
#endif

#define font_small font_14
#define font_large font_22

#endif
